Домашняя работа 2
BroSmithBoris/Qt_learn pull request #4
Opened 2020-03-27 18:06 UTC by BroSmithBoris

2020-03-28 17:21 UTC, tugolukovpn commented on Homework_2/Program/Homework_1.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Файл *.pro.user является файлов, содержащим пользовательские настройки проекта и не должен храниться в репозитории. Нужно использовать этот файл добавить в исключения в файле .gitignore.

2020-03-28 17:23 UTC, tugolukovpn commented on Homework_2/Program/main.qml
> +                        signUpButton.font.underline = false
У тебя хорошо сделан биндинг для Loader'а - его source зависит от того, какое значение у переменной "currentForm". Таким же образом стоит сделать с signInButton и signUpButton - только у этих объектов менять свойство font.underline в зависимости от значения свойства "currentForm".

2020-03-28 17:23 UTC, tugolukovpn commented on Homework_2/Program/main.qml
> +
Лишняя пустая строка.

2020-03-28 17:23 UTC, tugolukovpn commented on Homework_2/Server/Qt_project_2.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Этот файл должен быть так же добавлен в исключения в .gitignore.

2020-03-28 17:24 UTC, tugolukovpn commented on Homework_2/Server/authmanager.cpp
> +        this -> onRegisterFinished();
Данная лямбда - это уже обработчик твоего запроса. Не нужно в лябмде вызывать еще один обработчик. Он просто не нужен. Соответственно, либо к сигналу финиша запроса ты подключаешь лябмду, и делаешь все дела в ней. Либо К сигналу подключаешь слот, и все дела делаешь в нем. А так получается, что у тебя отдельная функция нужна что бы испустить сигнал о финише загрузки. Это излишне. Сигнал можно испустить и из самой лямбды.

2020-03-28 17:25 UTC, tugolukovpn commented on Homework_2/Server/authmanager.cpp
> +    emit registerRequestCompleted(this -> authenticateError);
Нет смысла хранить текст ошибки в поле класса. Если отправку сигнала перенести в лябмду, в которой ты получаешь текст ошибки, можно сразу в сигнал передать эту ошибку. Т.о. поля для хранения текстов ошибок не нужны.

2020-03-28 17:26 UTC, tugolukovpn commented on Homework_2/Server/authmanager.cpp
> +        this->onAuthenticateFinished();
См. ниже про использование лябмды и функций как обработчиков запроса.

2020-03-28 17:26 UTC, tugolukovpn commented on Homework_2/Server/authmanager.h
> +
Лишняя пустая строка.

2020-04-01 13:25 UTC, mashinapetro requested changes

2020-04-01 13:25 UTC, mashinapetro commented on Homework_2/Program/Homework_1.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Файлы *.pro.user нужно удалить из под контроля git'а и добавить в файл .gitignore.

2020-04-01 13:25 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                        signUpButton.font.underline = false
Подчеркивание меток необходимо реализовать так же, как и загрузки компонентов в Loader'е - с помощью биндингов. В обработчике сигнала onClicked должно остаться только изменение свойство currentForm.

2020-04-01 13:25 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +
Лишняя пустая строка.

2020-04-01 13:25 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                        signInButton.font.underline = false
Здесь так же лишнее надо убрать, должно остаться только изменение свойство currentForm.

2020-04-01 13:25 UTC, mashinapetro commented on Homework_2/Server/Qt_project_2.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Файлы *.pro.user должны быть удалены из под контроля git'а и добавлены в .gitignore.

2020-04-01 13:25 UTC, mashinapetro commented on Homework_2/Server/authmanager.cpp
> +        this->onAuthenticateFinished();
Здесь не надо использовать дополнительную функцию, что бы испустить сигнал о выполнении запроса. 
Посмотри видео с разбором частых ошибок.

2020-04-01 13:25 UTC, mashinapetro commented on Homework_2/Server/authmanager.cpp
> +        this -> onRegisterFinished();
Здесь так же не нужна доп. функция для отправки сигнала.

2020-04-01 13:25 UTC, mashinapetro commented on Homework_2/Server/authmanager.h
> +    void onRegisterFinished();
В сигнале о выполнении запроса на регистрацию необходимо передавать строку с ошибкой. Если ошибки нет - строка должна быть пустая.

2020-04-01 13:25 UTC, mashinapetro commented on Homework_2/Server/authmanager.h
> +    void onAuthenticateFinished();
В сигнале о выполнении запроса на авторизацию необходимо передавать строку с ошибкой и токен. Если ошибки нет - строка должна быть пустая. Если ошибка есть, строка с токеном должна быть пустой.

2020-04-02 10:44 UTC, BroSmithBoris commented on Homework_2/Program/Homework_1.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Удалил

2020-04-02 10:44 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +                        signUpButton.font.underline = false
Удалил

2020-04-02 10:44 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +
Убрал

2020-04-02 10:45 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +                        signInButton.font.underline = false
Убрал

2020-04-02 10:45 UTC, BroSmithBoris commented on Homework_2/Server/Qt_project_2.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Удалил

2020-04-02 10:45 UTC, BroSmithBoris commented on Homework_2/Server/authmanager.cpp
> +        this->onAuthenticateFinished();
Решил проблему

2020-04-02 10:45 UTC, BroSmithBoris commented on Homework_2/Server/authmanager.cpp
> +        this -> onRegisterFinished();
Убрал доп. функцию

2020-04-02 10:45 UTC, BroSmithBoris commented on Homework_2/Server/authmanager.h
> +    void onRegisterFinished();
Сделал

2020-04-02 10:45 UTC, BroSmithBoris commented on Homework_2/Server/authmanager.h
> +    void onAuthenticateFinished();
Сделал

2020-04-03 07:08 UTC, mashinapetro commented on Homework_2/Program/Homework_1.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Ок.

2020-04-03 07:08 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                        signUpButton.font.underline = false
Ок.

2020-04-03 07:10 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                onClicked: (currentForm == "sign_up") ? currentForm = "sign_in" : currentForm = "sign_up"
WAT? Почему у тебя обработчик внутри обработчика?
И почему у тебя currentForm изменяется очень странно?
При нажатии на singInButton currentForm должна принимать значение "sign_in". И все. Больше никакое другое значение не должно приниматься.

2020-04-03 07:10 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +            onClicked: {
Тут тоже беда с обработчиком внутри обработчика.

2020-04-03 07:10 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +            font.underline: (currentForm == "sign_in") ? true : false
Выражение `(currentForm == "sign_in")` уже является логическим, т.е. на выходе будет true или false. Тернарный оператор здесь не надо использовать.

2020-04-03 07:10 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +            font.underline: (currentForm == "sign_up") ? true : false
Тут так же не надо использовать тернарный оператор.

2020-04-03 07:10 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +
Ок.

2020-04-03 07:11 UTC, mashinapetro commented on Homework_2/Server/authmanager.cpp
> +        this -> onRegisterFinished();
Ок.

2020-04-03 07:21 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +                onClicked: (currentForm == "sign_up") ? currentForm = "sign_in" : currentForm = "sign_up"
Исправил

2020-04-03 07:22 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +            onClicked: {
Исправил

2020-04-03 07:22 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +            font.underline: (currentForm == "sign_in") ? true : false
Исправил

2020-04-03 07:22 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +            font.underline: (currentForm == "sign_up") ? true : false
Исправил

2020-04-03 09:53 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                currentForm == "sign_up" ? currentForm = "sign_in" : currentForm = "sign_up"
При нажатии на эту кнопку необходимо устанавливать значение currentForm в sign_up. 
Твой код работает следующим образом: если два раза нажать на кнопку "sign_in", то значение currentForm будет "sign_up", а это неправильно.

2020-04-03 09:53 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                currentForm == "sign_in" ? currentForm = "sign_up" : currentForm = "sign_in"
Здесь тернарный оператор не нужен. При нажатии на эту кнопку значение currentForm должно устанавливаться только в "sign_up".

2020-04-03 09:53 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +            onClicked: {
Ок.

2020-04-03 09:53 UTC, mashinapetro commented on Homework_2/Server/Qt_project_2.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Ок.

2020-04-03 09:54 UTC, mashinapetro commented on Homework_2/Server/authmanager.cpp
> +        this->onAuthenticateFinished();
Ок.

2020-04-03 09:55 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +            font.underline: (currentForm == "sign_up") ? true : false
Ок.

2020-04-03 09:55 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +            font.underline: (currentForm == "sign_in") ? true : false
Ок.

2020-04-03 10:25 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +                currentForm == "sign_up" ? currentForm = "sign_in" : currentForm = "sign_up"
Исправил

2020-04-03 10:25 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +                currentForm == "sign_in" ? currentForm = "sign_up" : currentForm = "sign_in"
Исправил

2020-04-03 10:31 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                cursorShape: Qt.PointingHandCursor
В обработчике нельзя таким образом устанавливать свойства.

2020-04-03 10:31 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                cursorShape: Qt.PointingHandCursor
В обработчике нельзя таким образом устанавливать свойства.

2020-04-03 10:31 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                currentForm == "sign_in" ? currentForm = "sign_up" : currentForm = "sign_in"
Ок.

2020-04-03 10:31 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                currentForm == "sign_up" ? currentForm = "sign_in" : currentForm = "sign_up"
Ок.

2020-04-03 11:59 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +                cursorShape: Qt.PointingHandCursor
Исправил

2020-04-03 11:59 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +                cursorShape: Qt.PointingHandCursor
Исправил

2020-04-03 18:58 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                currentForm == "sign_in" ? currentForm = "sign_up" : currentForm = "sign_in"
Ок.

2020-04-03 18:58 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                cursorShape: Qt.PointingHandCursor
Ок.

2020-04-03 18:58 UTC, mashinapetro commented on Homework_2/Program/main.qml
> +                cursorShape: Qt.PointingHandCursor
Ок.

2020-04-03 19:00 UTC, mashinapetro requested changes

2020-04-03 19:00 UTC, mashinapetro commented on Homework_2/Program/qml/SignInForm.qml
> +        echoMode: "Password"
У этого свойства неверное значение. Тут должен быть enumeration, а не строка.

2020-04-03 19:00 UTC, mashinapetro commented on Homework_2/Program/qml/SignUpForm.qml
> +        echoMode: "Password"
У этого свойства неверное значение. Тут должен быть enumeration, а не строка.

2020-04-03 19:00 UTC, mashinapetro commented on Homework_2/Program/qml/SignUpForm.qml
> +        echoMode: "Password"
У этого свойства неверное значение. Тут должен быть enumeration, а не строка.

2020-04-04 02:40 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignUpForm.qml
> +        echoMode: "Password"
Исправил

2020-04-04 02:40 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignUpForm.qml
> +        echoMode: "Password"
Исправил

2020-04-04 02:40 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        echoMode: "Password"
Исправил

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Program/ClickableText.qml
> +    color: bottomButtonColor
А если использовать clickableText в другом внешнем компоненте, в котором нет свойств bottomButtonSize и bottomButtonColor?

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Program/main.qml
> +                : "qrc:/qml/SignUpForm.qml"
Условие будет расширятся с добавлением новых форм. Лучше используй словарь, тогда свойство source будет занимать одну строчку кода при при любом количестве форм.

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignInForm.qml
> +        color: titleTextColor
Старайся не использовать внешние свойства в компоненте. Так становится тяжелее его переиспользовать в других внешних компонентах.

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignInForm.qml
> +        width: signIn.width - marginIndent
Здесь то же самое.

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignInForm.qml
> +        font.pixelSize: textFieldSize
И здесь.

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignUpForm.qml
> +        font.pixelSize: titleTextSize
Та же самая проблема с использованием внешних свойств.

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignUpForm.qml
> +    }
Вместо кучи якорей удобнее использовать компонент Column, в нем не нужно привязывать элементы друг к другу.

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Server/authmanager.h
> +    void authenticateRequestCompleted(QString, QString);
Где названия аргументов? Что в них передается?

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignUpForm.qml
> +        echoMode: "Password"
Ок.

2020-04-04 05:39 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignUpForm.qml
> +        echoMode: "Password"
Ок.

2020-04-04 05:40 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignInForm.qml
> +        echoMode: "Password"
Ок.

2020-04-04 05:55 UTC, BroSmithBoris commented on Homework_2/Program/ClickableText.qml
> +    color: bottomButtonColor
ок

2020-04-04 05:55 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +                : "qrc:/qml/SignUpForm.qml"
ок

2020-04-04 05:55 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        color: titleTextColor
ок

2020-04-04 05:55 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        width: signIn.width - marginIndent
ок

2020-04-04 05:55 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        font.pixelSize: textFieldSize
ок

2020-04-04 05:55 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignUpForm.qml
> +        font.pixelSize: titleTextSize
ок

2020-04-04 05:55 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignUpForm.qml
> +    }
ок

2020-04-04 05:56 UTC, BroSmithBoris commented on Homework_2/Server/authmanager.h
> +    void authenticateRequestCompleted(QString, QString);
исправил

2020-04-05 11:43 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        color: titleTextColor
Частично согласен с замечанием, все же считаю, значение лучше выделять в отдельные переменные для более легкого редактирования объектов.

2020-04-05 11:44 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        width: signIn.width - marginIndent
Частично согласен с замечанием, все же считаю, значение лучше выделять в отдельные переменные, для более легкого редактирования объектов.

2020-04-05 11:44 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        font.pixelSize: textFieldSize
Частично согласен с замечанием, все же считаю, значение лучше выделять в отдельные переменные для более легкого редактирования объектов.

2020-04-05 11:49 UTC, BroSmithBoris commented on Homework_2/Program/ClickableText.qml
> +    color: bottomButtonColor
По ТЗ clickableText нельзя использовать вне main.qml.
Но все же да, передавать значения из main.qml сюда не рекомендуется.
Учту в дальнейшем.

2020-04-05 11:51 UTC, BroSmithBoris commented on Homework_2/Program/main.qml
> +                : "qrc:/qml/SignUpForm.qml"
При расширении словарь будет менее производительнее, лучше использовать, к примеру, массив или список.

2020-04-05 11:53 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignUpForm.qml
> +    }
ТЗ не подразумевало использование Column, но да, так будет лучше.
Учту на будущее.

2020-04-05 11:55 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignUpForm.qml
> +        font.pixelSize: titleTextSize
Да, передавать значения из main.qml сюда не рекомендуется.
Учту в дальнейшем.

2020-04-05 12:06 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        font.pixelSize: textFieldSize
Исправил.

2020-04-05 12:06 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        width: signIn.width - marginIndent
Исправил.

2020-04-05 12:06 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignInForm.qml
> +        color: titleTextColor
Исправил.

2020-04-05 12:07 UTC, BroSmithBoris commented on Homework_2/Program/ClickableText.qml
> +    color: bottomButtonColor
Исправил.

2020-04-05 12:07 UTC, BroSmithBoris commented on Homework_2/Program/qml/SignUpForm.qml
> +        font.pixelSize: titleTextSize
Исправил.

2020-04-05 13:07 UTC, IAlmostDeveloper commented on Homework_2/Program/main.qml
> +                : "qrc:/qml/SignUpForm.qml"
Ок.

2020-04-05 13:07 UTC, IAlmostDeveloper commented on Homework_2/Server/authmanager.h
> +    void authenticateRequestCompleted(QString, QString);
Ок.

2020-04-05 13:07 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignUpForm.qml
> +    }
Ок.

2020-04-05 13:08 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignUpForm.qml
> +        font.pixelSize: titleTextSize
Ок.

2020-04-05 13:15 UTC, IAlmostDeveloper commented on Homework_2/Program/ClickableText.qml
> +    color: bottomButtonColor
Ок.

2020-04-05 13:15 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignInForm.qml
> +        color: titleTextColor
Ок.

2020-04-05 13:15 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignInForm.qml
> +        width: signIn.width - marginIndent
Ок.

2020-04-05 13:15 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignInForm.qml
> +        font.pixelSize: textFieldSize
Ок.

2020-04-05 13:15 UTC, IAlmostDeveloper commented on Homework_2/Program/qml/SignUpForm.qml
> +        font.pixelSize: titleTextSize
Ок.

2020-04-06 06:40 UTC, mashinapetro approved these changes

2020-04-07 04:29 UTC, merged